import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  EN: {
    home: 'Home',
    waterStatus: 'Water Status',
    liveMap: 'Live Map',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    outages: 'Scheduled Outages',
    privacy: 'Privacy Policy',
    reportIssue: 'Report Water Issue',
    myProfile: 'My Profile',
    dashboard: 'Resident Dashboard',
    commandCenter: 'Command Center',
    alerts: 'Water Alerts',
    notifications: 'Notifications',
    damMonitoring: 'Dam Level Monitoring',
    liveTrucks: 'Live Mobile Tankers',
    currentTrip: 'Today Assigned Trip',
    routeStops: 'Route Delivery Stops',
    manageDams: 'Dams & Readings',
    manageTrucks: 'Fleet & Drivers',
    manageRoutes: 'Routes & Stops',
    manageUsers: 'Users & Roles',
    broadcastAlerts: 'Broadcast Emergency Alert',
    reportsHistory: 'Reports & Analytics',
    publicPortal: 'Public Portal',
    view: 'View',
    role: 'Role',
    resident: 'Resident',
    driver: 'Water Tanker Driver',
    admin: 'Sol Plaatje Municipal Admin',
    logout: 'Sign Out',
    systemLive: 'System Operational',
    residentView: 'Resident View',
    driverView: 'Driver View',
    adminView: 'Admin View',
    password: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    emailAddress: 'Email Address',
    fullName: 'Full Name',
    suburbArea: 'Suburb / Area',
    preferredLanguage: 'Preferred Language',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirm: 'Confirm',
    arrived: 'Arrived',
    startDelivery: 'Start Delivery',
    deliveryCompleted: 'Delivery Completed',
    approxLitres: 'Approximate Litres Delivered',
    deliveryNotes: 'Notes / Remarks',
    motto: 'Elke druppel tel • Metsi ke bophelo',
    subheading: 'Sol Plaatje Municipality — Kimberley Water Portal',
    emergencyHotlines: 'Emergency Hotlines',
    response247: '24/7 Water Emergency Line',
    callCentre: 'Sol Plaatje Call Centre',
    heroTitle: 'Kimberley water supply & tanker operations',
    heroDesc: 'Check daily dam storage levels, view scheduled water service interruptions, and track mobile delivery tankers across Sol Plaatje Municipality in real time.',
    checkWaterStatus: 'Check water status',
    trackActiveTankers: 'Track active tankers',
    residentLogin: 'Resident & Staff Portal Access',
    enterEmail: 'Email address',
    enterPassword: 'Password',
    loginButton: 'Sign in to Portal',
    registerTitle: 'Resident Registration',
    verifyEmail: 'Verify Email Address',
    otpLabel: 'Enter 6-digit OTP Code',
    verifyButton: 'Verify & Activate Account',
    resendOtp: 'Resend new OTP',
    aboutTitle: "Protecting Kimberley's water supply, drop by drop.",
    aboutDesc: "AquaBophelo (Bophelo meaning 'Life') is Sol Plaatje Municipality's digital water monitoring and real-time tanker tracking platform, engineered for the residents of Kimberley, Northern Cape.",
    realtimeStorage: 'Real-time dam storage',
    realtimeStorageDesc: 'Provides daily storage level monitoring across Newton Reservoir and Riverton Water Works in MegaLitres (ML) with certified operational status bands.',
    liveTankerMap: 'Live water tanker map',
    liveTankerMapDesc: 'Tracks municipal delivery trucks moving through Galeshewe, Roodepan, and Kimberley Central, giving residents live GPS locations and estimated arrival times.',
    verifiedEmailNotifications: 'Verified email notifications',
    verifiedEmailNotificationsDesc: 'Sends instant email alerts for water outages, delivery route updates, and dam status changes directly to subscribed residents.',
    noticeBanner: 'Scheduled Maintenance Notice: Pipe repairs ongoing in Galeshewe Zone 3. Mobile water tankers are actively delivering backup supply.',
    readNoticeDetails: 'Read Notice Details',
    activeTankersEnRoute: 'active water tankers en route',
    live: 'Live',
    quickAccessPortal: 'Quick Access Portal',
    reportIssueDesc: 'Report a leak, burst pipe, or water outage in your neighborhood directly to Sol Plaatje engineering team.',
    waterInterruptionSchedule: 'Water Interruption Schedule',
    contactTitle: 'Get in touch with Sol Plaatje Water Department',
    contactDesc: 'Have a question, feedback, or need emergency water assistance in Kimberley? Reach out to our 24/7 operations desk.',
    yourName: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    sendMessage: 'Send Message',
    privacyTitle: 'AquaBophelo Data Privacy & Protection Policy',
    privacyDesc: 'Sol Plaatje Municipality is committed to protecting resident data and ensuring secure digital water management.',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordDesc: 'Enter your registered email address and we will send you an OTP code to reset your password.',
    sendOtp: 'Send OTP Code',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    resetPasswordButton: 'Reset Password',
    backToLogin: 'Back to Sign In',
    termsCheckbox: 'I agree to Sol Plaatje Municipal Water System Terms & Conditions',

    /* Additional Comprehensive Global UI Translations */
    solPlaatjeMun: 'Sol Plaatje Municipality',
    kimberleyOperations: 'Kimberley Water Operations Desk',
    emergencyLine: 'Emergency Hotline: 053 830 6100',
    submitInquiry: 'Submit Municipal Inquiry',
    goToPortal: 'Go to portal',
    aalRiverJourney: 'How Kimberley Water Reaches Your Home',
    journeySubtitle: 'The Journey from Vaal River to Your Tap',
    journeyDesc: 'Sol Plaatje Municipality manages an interconnected purification and distribution network to serve Kimberley residents.',
    step1Title: 'Vaal River Extraction',
    step1Desc: 'Raw water is drawn from the Vaal River at the Riverton Extraction Station north of Kimberley.',
    step2Title: 'Riverton Water Works',
    step2Desc: 'Purification, filtration, and quality testing treat water to South African SANS 241 drinking standards.',
    step3Title: 'Newton Reservoir',
    step3Desc: 'Bulk storage tanks hold up to 92.5 MegaLitres to pressurize supply pipelines across Kimberley.',
    step4Title: 'Mobile Tankers',
    step4Desc: 'During scheduled maintenance or pipe repairs, GPS-tracked tankers deliver clean water directly to suburb distribution stops.',
    liveZoneTelemetry: 'Live Zone Telemetry',
    waterStatusByArea: 'Kimberley Water Status by Area',
    statusVerifiedDesc: 'Current operational status verified by Sol Plaatje Municipal Control Center.',
    realtimeGpsTracking: 'Real-Time GPS Tracking',
    liveTankerRadar: 'Live Mobile Tanker Radar',
    radarDesc: 'Click vehicle pins on the map below to inspect driver ratings, active routes, and estimated arrival times.',
    infrastructureEmergency: 'Municipal Infrastructure Emergency',
    noticeBurstTitle: 'Notice a Pipe Burst or Water Main Leak?',
    noticeBurstDesc: 'Report infrastructure damage, bursting pipes, or contaminated water directly to Sol Plaatje municipal engineers to prevent water loss and accelerate emergency repairs.',
    reportWaterIssueNow: 'Report Water Issue Now',
    contactMunicipalDesk: 'Contact Municipal Desk',
    knowYourSystem: 'Know your water system',
    knowYourSystemDesc: 'How AquaBophelo connects Sol Plaatje Municipality staff, tanker drivers, and Kimberley residents in one transparent ecosystem.',
    damLevelEntry: 'Dam level entry',
    damLevelEntryDesc: 'Municipal engineers record certified gauge level readings daily at Newton & Riverton.',
    autoThresholds: 'Automated thresholds',
    autoThresholdsDesc: 'System evaluates levels: Healthy (≥60%), Watch (30-60%), Critical (<30%).',
    liveGpsTelemetry: 'Live GPS telemetry',
    liveGpsTelemetryDesc: 'Water tanker drivers broadcast live coordinates while making scheduled delivery stops.',
    residentEmpowerment: 'Resident empowerment',
    residentEmpowermentDesc: 'Residents track trucks on the live map, receive email notices, and report leaks directly.',
    officialAuth: 'Official Sol Plaatje municipal authentication',
    dontHaveAccount: "Don't have an account yet?",
    alreadyRegistered: 'Already registered?',
    phoneNumber: 'Phone Number',
    phoneUsageNote: 'Used for municipal notification broadcasts & tanker dispatch updates',
    passwordsMatch: 'Passwords match',
    passwordsDontMatch: 'Passwords do not match',
    sendVerificationCode: 'Send verification code',
    popiaPrivacyTitle: 'POPIA & Municipal Data Privacy Policy',
    privacySubtitle: 'AquaBophelo Privacy & Data Transparency',
    privacySummary: 'Sol Plaatje Local Municipality is committed to protecting the privacy, personal information, and location telemetry of Kimberley residents and water tanker operators.',
    whoCanSeeInfo: '1. Who can see my information?',
    whoCanSeeInfoDesc: 'Your registered resident account information (Name, Email, Phone Number, and Residential Suburb) is kept strictly confidential within the Sol Plaatje Municipal Water Management Department.',
    locationSharing: '2. Location Sharing & Telemetry',
    locationSharingDesc: 'GPS telemetry is broadcast exclusively by authorized municipal water delivery trucks to inform residents of estimated arrival times.',
    dataSecurity: '3. Data Usage & Security Standards',
    dataSecurityDesc: 'System data is processed in compliance with South Africa\'s Protection of Personal Information Act (POPIA). User credentials are encrypted using modern cryptographic hashing standards.',
    officialPrivacyContacts: 'Official Privacy Contacts',
    privacyContactDesc: 'If you have any questions regarding your account data or wish to request data erasure, please email privacy@solplaatje.org.za or visit Sol Plaatje Civic Centre, Kimberley.',
    commandCenterActive: 'Command Center Active',
    utilityOperationsHub: 'Water Utility & Fleet Operations Hub',
    overview: 'Overview',
  },
  AF: {
    home: 'Tuis',
    waterStatus: 'Waterstatus',
    liveMap: 'Intydse Kaart',
    aboutUs: 'Oor Ons',
    contactUs: 'Kontak Ons',
    signIn: 'Meld Aan',
    createAccount: 'Skep Rekening',
    outages: 'Geskeduleerde Onderbrekings',
    privacy: 'Privaatheidsbeleid',
    reportIssue: 'Rapporteer Waterprobleem',
    myProfile: 'My Profiel',
    dashboard: 'Inwoner Paneelbord',
    commandCenter: 'Bevelsentrum',
    alerts: 'Water Waarskuwings',
    notifications: 'Kennisgewings',
    damMonitoring: 'Damvlak Monitoring',
    liveTrucks: 'Intydse Tenkwaens',
    currentTrip: 'Vandag se Aflewering',
    routeStops: 'Roete Halte',
    manageDams: 'Damme & Lesings',
    manageTrucks: 'Vloot & Bestuurders',
    manageRoutes: 'Roetes & Halte',
    manageUsers: 'Gebruikers & Rolle',
    broadcastAlerts: 'Saai Noodwaarskuwing Uit',
    reportsHistory: 'Verslae & Ontleding',
    publicPortal: 'Publieke Portaal',
    view: 'Bekyk',
    role: 'Rol',
    resident: 'Inwoner',
    driver: 'Tenkwa Bestuurder',
    admin: 'Sol Plaatje Munisipale Admin',
    logout: 'Meld Uit',
    systemLive: 'Stelsel Operasioneel',
    residentView: 'Inwoner Aansig',
    driverView: 'Bestuurder Aansig',
    adminView: 'Admin Aansig',
    password: 'Wagwoord',
    showPassword: 'Wys wagwoord',
    hidePassword: 'Versteek wagwoord',
    emailAddress: 'E-posadres',
    fullName: 'Volle Naam',
    suburbArea: 'Voorstad / Area',
    preferredLanguage: 'Verkose Taal',
    saveChanges: 'Stoort Veranderings',
    cancel: 'Kanselleer',
    confirm: 'Bevestig',
    arrived: 'Aangekom',
    startDelivery: 'Begin Aflewering',
    deliveryCompleted: 'Aflewering Voltooi',
    approxLitres: 'Benaderde Liter Afgelewer',
    deliveryNotes: 'Notas / Opmerkings',
    motto: 'Elke druppel tel • Metsi ke bophelo',
    subheading: 'Sol Plaatje Munisipaliteit — Kimberley Waterportaal',
    emergencyHotlines: 'Nood-blitslyn',
    response247: '24/7 Water Noodlyn',
    callCentre: 'Sol Plaatje Sorteersentrum',
    heroTitle: 'Kimberley watervoorsiening & tenkwa-bedrywighede',
    heroDesc: 'Kontroleer daaglikse damvlakke, bekyk geskeduleerde onderbrekings en spoor mobiele afleweringstenkwaens intyds oor Sol Plaatje munisipaliteit na.',
    checkWaterStatus: 'Kontroleer waterstatus',
    trackActiveTankers: 'Spoor tenkwaens na',
    residentLogin: 'Inwoner & Personeel Portaal Toegang',
    enterEmail: 'E-posadres',
    enterPassword: 'Wagwoord',
    loginButton: 'Meld Aan By Portaal',
    registerTitle: 'Inwoners Registrasie',
    verifyEmail: 'Verifieer E-posadres',
    otpLabel: 'Voer 6-syfer OTP Kode in',
    verifyButton: 'Verifieer & Aktiveer Rekening',
    resendOtp: 'Huur nuwe OTP',
    aboutTitle: 'Beskerm Kimberley se watervoorraad, druppel vir druppel.',
    aboutDesc: "AquaBophelo (Bophelo wat 'Lewe' beteken) is Sol Plaatje Munisipaliteit se digitale water- en intydse tenkwa-opsporingsplatform, ontwerp vir die inwoners van Kimberley, Noord-Kaap.",
    realtimeStorage: 'Intydse damopgaar',
    realtimeStorageDesc: 'Bied daaglikse monitoring van opgaarvlakke oor Newton Reservoir en Riverton Waterwerke in MegaLiter (ML) met gesertifiseerde operasionele statusse.',
    liveTankerMap: 'Intydse watertenkwa kaart',
    liveTankerMapDesc: 'Volg munisipale afleweringstrokke wat deur Galeshewe, Roodepan en Kimberley Sentraal beweeg, wat inwoners van intydse GPS-liggings en verwagte aankomstye voorsien.',
    verifiedEmailNotifications: 'Geverifieerde e-pos kennisgewings',
    verifiedEmailNotificationsDesc: 'Stuur onmiddellike e-pos waarskuwings vir wateronderbrekings, roete opdaterings en damvlak veranderings direk aan ingetekende inwoners.',
    noticeBanner: 'Kennisgewing van Geskeduleerde Instandhouding: Pypherstelwerk aan die gang in Galeshewe Sone 3. Mobiele watertenkwaens lewer aktief rugsteunvoorsiening.',
    readNoticeDetails: 'Lees Kennisgewing Besonderhede',
    activeTankersEnRoute: 'aktiewe watertenkwaens oppad',
    live: 'Intyds',
    quickAccessPortal: 'Vinnige Toegang Portaal',
    reportIssueDesc: "Rapporteer 'n lek, gebarste pyp of wateronderbreking in jou buurt direk aan Sol Plaatje ingenieurspan.",
    waterInterruptionSchedule: 'Wateronderbrekings Skedule',
    contactTitle: 'Kontak Sol Plaatje Waterdepartement',
    contactDesc: "Het jy 'n vraag, terugvoer of benodig jy noodwaterhulp in Kimberley? Kontak ons 24/7 operasionele toonbank.",
    yourName: 'Jou Naam',
    subject: 'Onderwerp',
    message: 'Boodskap',
    sendMessage: 'Stuur Boodskap',
    privacyTitle: 'AquaBophelo Data Privaatheid & Beskermingsbeleid',
    privacyDesc: 'Sol Plaatje Munisipaliteit is verbind tot die beskerming van inwonersdata en veilige digitale waterbestuur.',
    forgotPasswordTitle: 'Wagwoord Vergeet',
    forgotPasswordDesc: "Voer jou geregistreerde e-posadres in en ons sal vir jou 'n OTP-kode stuur om jou wagwoord te herstel.",
    sendOtp: 'Stuur OTP Kode',
    newPassword: 'Nuwe Wagwoord',
    confirmPassword: 'Bevestig Nuwe Wagwoord',
    resetPasswordButton: 'Herstel Wagwoord',
    backToLogin: 'Terug na Meld Aan',
    termsCheckbox: 'Ek stem in tot Sol Plaatje Munisipale Waterstelsel Bepalings & Voorwaardes',

    /* Additional Comprehensive Global UI Translations */
    solPlaatjeMun: 'Sol Plaatje Munisipaliteit',
    kimberleyOperations: 'Kimberley Water Kantoor',
    emergencyLine: 'Nood-blitslyn: 053 830 6100',
    submitInquiry: 'Indien Munisipale Navraag',
    goToPortal: 'Gaan na portaal',
    aalRiverJourney: 'Hoe Kimberley-water jou huis bereik',
    journeySubtitle: 'Die reis vanaf die Vaalrivier na jou kraan',
    journeyDesc: 'Sol Plaatje Munisipaliteit bestuur \'n onderling verbonde suiverings- en verspreidingsnetwerk om Kimberley-inwoners te bedien.',
    step1Title: 'Vaalrivier Onttrekking',
    step1Desc: 'Ruwe water word uit die Vaalrivier onttrek by die Riverton Onttrekkingsstasie noord van Kimberley.',
    step2Title: 'Riverton Waterwerke',
    step2Desc: 'Suivering, filtrasie en gehaltetoetsing behandel water volgens Suid-Afrikaanse SANS 241 drinkstandaarde.',
    step3Title: 'Newton Reservoir',
    step3Desc: 'Grootmaat opgaartenks hou tot 92.5 MegaLiter om toevoerpype oor Kimberley onder druk te hou.',
    step4Title: 'Mobiele Tenkwaens',
    step4Desc: 'Tydens geskeduleerde instandhouding of pypherstelwerk lewer GPS- nagespoorde tenkwaens skoon water direk aan buurthalte.',
    liveZoneTelemetry: 'Intydse Sone Telekommunikasie',
    waterStatusByArea: 'Kimberley Waterstatus per Area',
    statusVerifiedDesc: 'Huidige operasionele status geverifieer deur Sol Plaatje Munisipale Bevelsentrum.',
    realtimeGpsTracking: 'Intydse GPS-Opsporing',
    liveTankerRadar: 'Intydse Mobiele Tenkwa Radar',
    radarDesc: 'Klik op voertuigpenne op die kaart om bestuurdersbeoordelings, aktiewe roetes en verwagte aankomstye te sien.',
    infrastructureEmergency: 'Munisipale Infrastruktuur Noodgeval',
    noticeBurstTitle: 'Sien jy \'n pypbarste of waterlek?',
    noticeBurstDesc: 'Rapporteer infrastruktuurskade, pypbarste of besoedelde water direk aan Sol Plaatje ingenieurs om waterverlies te voorkom en noodherstelwerk te bespoedig.',
    reportWaterIssueNow: 'Rapporteer Waterprobleem Nou',
    contactMunicipalDesk: 'Kontak Munisipale Toonbank',
    knowYourSystem: 'Ken jou waterstelsel',
    knowYourSystemDesc: 'Hoe AquaBophelo Sol Plaatje Munisipaliteit personeel, tenkwa bestuurders en Kimberley inwoners in een deursigtige ekosisteem verbind.',
    damLevelEntry: 'Damvlak inskrywing',
    damLevelEntryDesc: 'Munisipale ingenieurs teken daagliks gesertifiseerde meteraflesings aan by Newton & Riverton.',
    autoThresholds: 'Outomatiese drempels',
    autoThresholdsDesc: 'Stelsel evalueer vlakke: Gesond (≥60%), Waaksaam (30-60%), Krities (<30%).',
    liveGpsTelemetry: 'Intydse GPS-telemetrie',
    liveGpsTelemetryDesc: 'Watertenkwa bestuurders saai intydse koördinate uit terwyl hulle geskeduleerde aflewerings doen.',
    residentEmpowerment: 'Inwoner bemagtiging',
    residentEmpowermentDesc: 'Inwoners spoor trokke op die kaart na, ontvang e-posse en rapporteer lekke direk.',
    officialAuth: 'Amptelike Sol Plaatje munisipale verifikasie',
    dontHaveAccount: 'Nog nie \'n rekening nie?',
    alreadyRegistered: 'Reeds geregistreer?',
    phoneNumber: 'Telefoonnommer',
    phoneUsageNote: 'Gebruik vir munisipale waarskuwings en tenkwa-opdaterings',
    passwordsMatch: 'Wagwoorde stem ooreen',
    passwordsDontMatch: 'Wagwoorde stem nie ooreen nie',
    sendVerificationCode: 'Stuur verifikasiekode',
    popiaPrivacyTitle: 'POPIA & Munisipale Data Privaatheidsbeleid',
    privacySubtitle: 'AquaBophelo Privaatheid & Data Deursigtigheid',
    privacySummary: 'Sol Plaatje Plaaslike Munisipaliteit is verbind tot die beskerming van privaatheid, persoonlike inligting en liggingtelemetrie van Kimberley-inwoners.',
    whoCanSeeInfo: '1. Wie kan my inligting sien?',
    whoCanSeeInfoDesc: 'Jou geregistreerde inwonerinligting word streng vertroulik gehou binne die Sol Plaatje Munisipale Waterbestuursdepartement.',
    locationSharing: '2. Ligging Deling & Telemetrie',
    locationSharingDesc: 'GPS-telemetrie word uitsluitlik deur gemagtigde munisipale watertenkwaens uitgesaai om inwoners van verwagte aankomstye in te lig.',
    dataSecurity: '3. Data Gebruik & Sekuriteit Standaarde',
    dataSecurityDesc: 'Stelseldata word verwerk volgens Suid-Afrika se Wet op die Beskerming van Persoonlike Inligting (POPIA). Gebruikersinligting word geënkripteer.',
    officialPrivacyContacts: 'Amptelike Privaatheid Kontakte',
    privacyContactDesc: 'As jy vrae het oor jou data of verwydering wil versoek, e-pos asseblief privacy@solplaatje.org.za of besoek Sol Plaatje Burgersentrum, Kimberley.',
    commandCenterActive: 'Bevelsentrum Aktief',
    utilityOperationsHub: 'Water- en Vlootoperasies Sentrum',
    overview: 'Oorsig',
  },
  TN: {
    home: 'Gae',
    waterStatus: 'Maemo a Metsi',
    liveMap: 'Mmapa wa Intydse',
    aboutUs: 'Ka Rona',
    contactUs: 'Ikgokaganye le Rona',
    signIn: 'Tsena',
    createAccount: 'Dira Akhaonto',
    outages: 'Thulaganyo ya Dikgaogo',
    privacy: 'Pholisi ya Sephiri',
    reportIssue: 'Begile Kgang ya Metsi',
    myProfile: 'Profayile ya Me',
    dashboard: 'Dashboto ya Badudi',
    commandCenter: 'Senthara ya Taolo',
    alerts: 'Ditsiboso tsa Metsi',
    notifications: 'Kitsiso',
    damMonitoring: 'Tlhatlhobo ya Matamo',
    liveTrucks: 'Dikoloi tsa Metsi',
    currentTrip: 'Leeto la Gompieno',
    routeStops: 'Diyemi tsa Tsela',
    manageDams: 'Matamo le Dipalo',
    manageTrucks: 'Dikoloi le Banelametsi',
    manageRoutes: 'Ditsela le Diyemi',
    manageUsers: 'Badirisi le Ditiro',
    broadcastAlerts: 'Rumela Tsiboso ya Tsoga',
    reportsHistory: 'Dipego le Dipalopalo',
    publicPortal: 'Portal ya Setšhaba',
    view: 'Bona',
    role: 'Tiro',
    resident: 'Modudi',
    driver: 'Moganni wa Koloi ya Metsi',
    admin: 'Molaodi wa Sol Plaatje',
    logout: 'Tswa',
    systemLive: 'Sistimi e Shoma',
    residentView: 'Pono ya Modudi',
    driverView: 'Pono ya Moganni',
    adminView: 'Pono ya Molaodi',
    password: 'Lekunutu',
    showPassword: 'Bontsha lekunutu',
    hidePassword: 'Fitlha lekunutu',
    emailAddress: 'Aterese ya Imeile',
    fullName: 'Leina ka Botlalo',
    suburbArea: 'Lefelo / Karolo',
    preferredLanguage: 'Puo e e Tlhophilweng',
    saveChanges: 'Boloka Diphetogo',
    cancel: 'Kanselera',
    confirm: 'Nnetefatsa',
    arrived: 'Gorogile',
    startDelivery: 'Simolola go Isa',
    deliveryCompleted: 'Go Isa Go Fedile',
    approxLitres: 'Dilitara tsa Metsi',
    deliveryNotes: 'Dintlha',
    motto: 'Elke druppel tel • Metsi ke bophelo',
    subheading: 'Masepala wa Sol Plaatje — Kimberley Water Portal',
    emergencyHotlines: 'Dinomoro tsa Tsoga',
    response247: 'Mogala wa Tsoga wa Metsi 24/7',
    callCentre: 'Setheo sa Megala sa Sol Plaatje',
    heroTitle: 'Phepelo ya metsi le dikoloi tsa metsi mo Kimberley',
    heroDesc: 'Lekola maemo a matamo a letsatsi le letsatsi, bona thulaganyo ya dikgaogo tsa metsi, le go latela dikoloi tsa metsi mo masepaleng wa Sol Plaatje.',
    checkWaterStatus: 'Lekola maemo a metsi',
    trackActiveTankers: 'Latela dikoloi tsa metsi',
    residentLogin: 'Phomolo ya Badudi le Badiredi',
    enterEmail: 'Aterese ya Imeile',
    enterPassword: 'Lekunutu',
    loginButton: 'Tsena mo Portaleng',
    registerTitle: 'Ikwodise le Badudi',
    verifyEmail: 'Tlhatlhoba Aterese ya Imeile',
    otpLabel: 'Tsenya Khoutu ya OTP ya 6',
    verifyButton: 'Tlhatlhoba & Tsenya Akhaonto',
    resendOtp: 'Rumela OTP e Ntšha',
    aboutTitle: 'Sireletsa phepelo ya metsi mo Kimberley, thothobi ka thothobi.',
    aboutDesc: "AquaBophelo (Bophelo ho rewa 'Bophelo') ke sethala sa masepala wa Sol Plaatje sa go lekola metsi le go latela dikoloi tsa metsi, se diretsweng badudi ba Kimberley, Kapa Bokone.",
    realtimeStorage: 'Kabelo ya matamo a metsi',
    realtimeStorageDesc: 'E fana ka tlhatlhobo ya matamo mo Newton Reservoir le Riverton Water Works mo MegaLitres (ML).',
    liveTankerMap: 'Mmapa wa dikoloi tsa metsi',
    liveTankerMapDesc: 'Latela dikoloi tsa masepala tsa metsi mo Galeshewe, Roodepan, le Kimberley Central.',
    verifiedEmailNotifications: 'Kitsiso tsa imeile tse netefalitsweng',
    verifiedEmailNotificationsDesc: 'E rumela ditsiboso tsa metsi, dikgaogo, le diphetogo tsa matamo ka imeile.',
    noticeBanner: 'Tsebiso ya Tokiso: Ditokiso tsa diphaephe di tsweletse mo Galeshewe Zone 3. Dikoloi tsa metsi di nesa metsi a dithuso.',
    readNoticeDetails: 'Bala Dintlha tsa Tsebiso',
    activeTankersEnRoute: 'dikoloi tsa metsi tse tsamayang',
    live: 'Intyds',
    quickAccessPortal: 'Portal ya Potlako',
    reportIssueDesc: 'Bega go dutla ga metsi, phaephe e thubegileng, kapa kgaogo mo lefelong la gago direki go setlhopha sa masepala.',
    waterInterruptionSchedule: 'Thulaganyo ya Dikgaogo tsa Metsi',
    contactTitle: 'Ikgokaganye le Lefapha la Metsi la Sol Plaatje',
    contactDesc: 'O na le potso, maikutlo, kapa o tlhoka thusego ya metsi mo Kimberley? Ikgokaganye le rona 24/7.',
    yourName: 'Leina la Gago',
    subject: 'Setlhogo',
    message: 'Molaetsa',
    sendMessage: 'Rumela Molaetsa',
    privacyTitle: 'Pholisi ya Sephiri le Tshireletso ya AquaBophelo',
    privacyDesc: 'Masepala wa Sol Plaatje o ikgafile go tshireletso ya data ya badudi le tsamaiso e e babalesegileng ya metsi.',
    forgotPasswordTitle: 'Lehetse Lekunutu',
    forgotPasswordDesc: 'Tsenya aterese ya gago ya imeile mme re tla go rumela khoutu ya OTP go busetsa lekunutu.',
    sendOtp: 'Rumela Khoutu ya OTP',
    newPassword: 'Lekunutu le Ntšha',
    confirmPassword: 'Nnetefatsa Lekunutu le Ntšha',
    resetPasswordButton: 'Busetse Lekunutu',
    backToLogin: 'Boela ko Tsena',
    termsCheckbox: 'Ke dumalana le Melao le Dipehelo tsa Masepala wa Sol Plaatje',

    /* Additional Comprehensive Global UI Translations */
    solPlaatjeMun: 'Masepala wa Sol Plaatje',
    kimberleyOperations: 'Setheo sa Metsi sa Kimberley',
    emergencyLine: 'Mogala wa Tsoga: 053 830 6100',
    submitInquiry: 'Rumela Potso ya Masepala',
    goToPortal: 'Eya mo portaleng',
    aalRiverJourney: 'Ka moo metsi a Kimberley a gorogang mo gae',
    journeySubtitle: 'Leeto go tswa Noka ya Vaal go ya pompong',
    journeyDesc: 'Masepala wa Sol Plaatje o tsamaisa thulaganyo ya phepafatso le phatlalatso ya metsi mo baduding ba Kimberley.',
    step1Title: 'Go Ntsha Metsi mo Nokeng ya Vaal',
    step1Desc: 'Metsi a ntshetswa mo Nokeng ya Vaal ko Riverton bokone ba Kimberley.',
    step2Title: 'Setheo sa Metsi sa Riverton',
    step2Desc: 'Phepafatso le tlhatlhobo ya metsi ho ya ka maemo a SANS 241 a Aferika Borwa.',
    step3Title: 'Letamo la Newton',
    step3Desc: 'Ditanka tse kgolo di tshwara dilitara tse 92.5 ML go isa metsi mo Kimberley.',
    step4Title: 'Dikoloi tsa Metsi',
    step4Desc: 'Ka nako ya ditokiso, dikoloi tsa metsi di isa metsi a a phepa mo diyeming tsa metsana.',
    liveZoneTelemetry: 'Maemo a Intydse a Sone',
    waterStatusByArea: 'Maemo a Metsi a Kimberley ka Karolo',
    statusVerifiedDesc: 'Maemo a gompieno a netefalitswe ke Setheo sa Taolo sa Masepala wa Sol Plaatje.',
    realtimeGpsTracking: 'Tshupetso ya GPS ya Intydse',
    liveTankerRadar: 'Radara ya Dikoloi tsa Metsi',
    radarDesc: 'Kanya mo dikoloing mo mmapeng go bona maemo a banelametsi, ditsela, le nako ya goroga.',
    infrastructureEmergency: 'Tsoga ya Mananeokgwebo a Masepala',
    noticeBurstTitle: 'A o bona leki kapa phaephe e thubegileng?',
    noticeBurstDesc: 'Bega tshenyo ya diphaephe kapa metsi a a kgotlelegileng direki go baenjineere ba Sol Plaatje go thibela tahlehelo ya metsi.',
    reportWaterIssueNow: 'Bega Kgang ya Metsi Swale',
    contactMunicipalDesk: 'Ikgokaganye le Masepala',
    knowYourSystem: 'Tseba sistimi ya gago ya metsi',
    knowYourSystemDesc: 'Ka moo AquaBophelo e kopanyang badiredi ba Sol Plaatje, banelametsi, le badudi ba Kimberley.',
    damLevelEntry: 'Keno ya maemo a matamo',
    damLevelEntryDesc: 'Baenjineere ba masepala ba kwadisa dipalo tsa matamo letsatsi le letsatsi mo Newton & Riverton.',
    autoThresholds: 'Dipehelo tsa itirisa',
    autoThresholdsDesc: 'Sistimi e lekola maemo: Sentle (≥60%), Tlhokomelo (30-60%), Maswe (<30%).',
    liveGpsTelemetry: 'Tshupetso ya GPS ya Intydse',
    liveGpsTelemetryDesc: 'Banelametsi ba rumela GPS ya intydse fa ba emang mo diyeming tsa thulaganyo.',
    residentEmpowerment: 'Kaelo ya Badudi',
    residentEmpowermentDesc: 'Badudi ba latela dikoloi mo mmapeng, ba amogela di-imeile, mme ba bega ditshokolo direki.',
    officialAuth: 'Netefatso e e amogelesegileng ya Masepala wa Sol Plaatje',
    dontHaveAccount: 'A ga o na akhaonto gape?',
    alreadyRegistered: 'O kwadisitse kale?',
    phoneNumber: 'Nomoro ya Mogala',
    phoneUsageNote: 'E dirisiwa go rumela ditsiboso tsa masepala le opdatering tsa dikoloi',
    passwordsMatch: 'Makunutu a a tshwana',
    passwordsDontMatch: 'Makunutu ga a tshwane',
    sendVerificationCode: 'Rumela khoutu ya tlhatlhobo',
    popiaPrivacyTitle: 'Pholisi ya Sephiri sa Data ya POPIA & Masepala',
    privacySubtitle: 'Phediso le Sephiri sa Data sa AquaBophelo',
    privacySummary: 'Masepala wa Sol Plaatje o ikgafile go tshireletso ya sephiri le data ya badudi ba Kimberley.',
    whoCanSeeInfo: '1. Mang a ka bonang tshedimosetso ya me?',
    whoCanSeeInfoDesc: 'Tshedimosetso ya gago ya akhaonto e bolokilwe ka sephiri mo Lefapheng la Metsi la Masepala wa Sol Plaatje.',
    locationSharing: '2. Go Abela Lefelo le Telemetry',
    locationSharingDesc: 'GPS telemetry e gasiwa ke dikoloi tsa masepala tsa metsi go stibosa badudi ka nako ya goroga.',
    dataSecurity: '3. Tiriso ya Data le Maemo a Polokesego',
    dataSecurityDesc: 'Data ya sistimi e lerefilwe ka fa tlase ga molao wa POPIA wa Aferika Borwa. Dikhomphuta tsa badirisi di fitlhilwe.',
    officialPrivacyContacts: 'Dinomoro tsa Sephiri tse di Amogelesegileng',
    privacyContactDesc: 'Fa o na le dipotso ka data ya gago kapa o batla go e phimola, rumela imeile go privacy@solplaatje.org.za kapa o etele Setheo sa Sol Plaatje mo Kimberley.',
    commandCenterActive: 'Setheo sa Taolo se Shoma',
    utilityOperationsHub: 'Setheo sa Metsi le Taolo ya Dikoloi',
    overview: 'Tshobokanyo',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('aquabophelo_lang') || 'EN';
  });

  useEffect(() => {
    localStorage.setItem('aquabophelo_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export default LanguageContext;
